### ISSUE TITLE
Definition check after usage

### ISSUE THREAD

**Issue by Dalfons0** [devonfw/devon4node#19]
Hello, 

I was just looking the TODO example when I realised that in the _role.guard.ts_ there is an undefined check of a variable after being accessed in this [line](https://github.com/devonfw/devon4node/blob/680e5bd3316c07520895202b277048b2df39a61d/samples/todo/src/app/core/auth/guards/roles.guard.ts#L19).

P.D.: I would do a PR but I don't have time right now sorry :(

**Comment by dario-rodriguez** [comment]
Solved by PR #20
