### ISSUE TITLE
Login as waiter waiter

### ISSUE THREAD

**Issue by jdiazgon** [devonfw/devon4node#22]
As a developer, I want to be able to log-in using as username `waiter` and password `waiter` so that we have an standard way to access every application of devonfw.

In MyThaiStar and CobiGen generated front-ends we are able to log-in using `waiter` and password `waiter`. I would like to have the same for devon4node :)

**Comment by dario-rodriguez** [comment]
Hello Jaime,

There is a main difference between devon4j and devon4node. In devon4j the users are defined statically. In devon4node the users are defined in the database, so if you want to add the user waiter, you only need to add a entry in the database.

You can see an example here: https://github.com/devonfw/devon4node/blob/develop/samples/todo/src/migration/1571244245671-InsertData.ts
