### ISSUE TITLE
Samples step by step

### ISSUE THREAD

**Issue by jperalde** [devonfw/devon4node#28]
In step by step tutorial, step 4.IV and 5 aren't working due to outdated command lines:
 @ApiModelPropertyOptional()
@ApiUseTag

**Comment by jambulud** [comment]
Fixed.

The decorators' name have been updated:
@ApiModelPropertyOptional()  --> @ApiModelPropertyOptional()
@ApiUseTag() --> @ApiUseTag()

for more details check https://github.com/nestjs/swagger#migration-from-v3
